config/routes.rb
LaurensSite::Application.routes.draw do
  resources :visuals

  resources :homepage_tiles

  resources :posts

  get 'food' => 'homepage#index'
  get 'about' => 'homepage#index'

  root 'homepage#index'
end

app/models/homepage_tile.rb
class HomepageTile < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :visuals
  has_attached_file :cover_image
end

app/models/visual.rb
class Visual < ActiveRecord::Base

  belongs_to :post

  has_attached_file :upload, 
    :styles => { 
      :mini => "100x100",
      :sm => "400x300",
      :med => "1000x750",
      :lrg => "2000x15000" },
    :convert_options => {
      :mini => "-quality 85 -strip",
      :sm => "-quality 85 -strip",
      :med => "-quality 85 -strip",
      :lrg => "-quality 85 -strip" }

  validates_attachment_size :upload, :less_than => 3.megabytes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
  end

end

app/controllers/homepage_tiles_controller.rb
class HomepageTilesController < ApplicationController
  before_action :set_homepage_tile, only: [:show, :edit, :update, :destroy]

  # GET /homepage_tiles
  # GET /homepage_tiles.json
  def index
    @homepage_tiles = HomepageTile.all
  end

  # GET /homepage_tiles/1
  # GET /homepage_tiles/1.json
  def show
  end

  # GET /homepage_tiles/new
  def new
    @homepage_tile = HomepageTile.new
  end

  # GET /homepage_tiles/1/edit
  def edit
  end

  # POST /homepage_tiles
  # POST /homepage_tiles.json
  def create
    @homepage_tile = HomepageTile.new(homepage_tile_params)

    respond_to do |format|
      if @homepage_tile.save
        format.html { redirect_to @homepage_tile, notice: 'Homepage tile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @homepage_tile }
      else
        format.html { render action: 'new' }
        format.json { render json: @homepage_tile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homepage_tiles/1
  # PATCH/PUT /homepage_tiles/1.json
  def update
    respond_to do |format|
      if @homepage_tile.update(homepage_tile_params)
        format.html { redirect_to @homepage_tile, notice: 'Homepage tile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @homepage_tile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homepage_tiles/1
  # DELETE /homepage_tiles/1.json
  def destroy
    @homepage_tile.destroy
    respond_to do |format|
      format.html { redirect_to homepage_tiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homepage_tile
      @homepage_tile = HomepageTile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homepage_tile_params
      params.require(:homepage_tile).permit(:text)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :cover_image)
    end

end

app/controllers/visuals_controller.rb
class VisualsController < ApplicationController
  before_action :set_visual, only: [:show, :edit, :update, :destroy]

  # GET /visuals
  # GET /visuals.json
  def index
    @visuals = Visual.all
  end

  # GET /visuals/1
  # GET /visuals/1.json
  def show
  end

  # GET /visuals/new
  def new
    @visual = Visual.new
  end

  # GET /visuals/1/edit
  def edit
  end

  # POST /visuals
  # POST /visuals.json
  def create
    @visual = Visual.new(visual_params)

    respond_to do |format|
      if @visual.save
        format.html { redirect_to @visual, notice: 'Visual was successfully created.' }
        format.json { render action: 'show', status: :created, location: @visual }
      else
        format.html { render action: 'new' }
        format.json { render json: @visual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visuals/1
  # PATCH/PUT /visuals/1.json
  def update
    respond_to do |format|
      if @visual.update(visual_params)
        format.html { redirect_to @visual, notice: 'Visual was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @visual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visuals/1
  # DELETE /visuals/1.json
  def destroy
    @visual.destroy
    respond_to do |format|
      format.html { redirect_to visuals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visual
      @visual = Visual.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visual_params
      params.require(:visual).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/homepage_tiles_helper.rb
module HomepageTilesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/visuals_helper.rb
module VisualsHelper
end

app/views/homepage/index.html.erb
<div id="filler-container" class="js-masonry">
  <div class="poster">
    <%= image_tag 'filler/filler1.jpg' %>
  </div>
  <div class="poster">
    <%= image_tag 'filler/filler2.jpg' %>
  </div>
  <div class="poster">
    <%= image_tag 'filler/filler3.jpg' %>
  </div>
  <div class="poster">
    <%= image_tag 'filler/filler4.jpg' %>
  </div>
  <div class="poster">
    <%= image_tag 'filler/filler5.jpg' %>
  </div>
  <div class="poster">
    <%= image_tag 'filler/filler6.jpg' %>
  </div>
  <div class="poster">
    <%= image_tag 'filler/filler7.jpg' %>
  </div>
</div>

app/views/homepage_tiles/_form.html.erb
<%= form_for(@homepage_tile) do |f| %>
  <% if @homepage_tile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homepage_tile.errors.count, "error") %> prohibited this homepage_tile from being saved:</h2>

      <ul>
      <% @homepage_tile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homepage_tiles/edit.html.erb
<h1>Editing homepage_tile</h1>

<%= render 'form' %>

<%= link_to 'Show', @homepage_tile %> |
<%= link_to 'Back', homepage_tiles_path %>

app/views/homepage_tiles/index.html.erb
<h1>Listing homepage_tiles</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @homepage_tiles.each do |homepage_tile| %>
      <tr>
        <td><%= homepage_tile.text %></td>
        <td><%= link_to 'Show', homepage_tile %></td>
        <td><%= link_to 'Edit', edit_homepage_tile_path(homepage_tile) %></td>
        <td><%= link_to 'Destroy', homepage_tile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homepage tile', new_homepage_tile_path %>

app/views/homepage_tiles/new.html.erb
<h1>New homepage_tile</h1>

<%= render 'form' %>

<%= link_to 'Back', homepage_tiles_path %>

app/views/homepage_tiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @homepage_tile.text %>
</p>

<%= link_to 'Edit', edit_homepage_tile_path(@homepage_tile) %> |
<%= link_to 'Back', homepage_tiles_path %>

app/views/layouts/_nav.html.erb
<div id="site-title">
  <div class="img"><%= image_tag('owls2.png') %></div>
  <div class="text">
    <h4>Galavanting</h4>
    <p>the</p>
    <h4>Globe</h4>
  </div>
</div>
<nav id="navigation">
  <div class="nav-item">
    <%= link_to "Blog", "/posts", :method => :get %>
  </div>
  <div class="nav-item">
    <%= link_to "Food", "/food", :method => :get %>
  </div>
  <div class="nav-item">
    <%= link_to "About", "/about", :method => :get %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LaurensSite</title>
  <script type="text/javascript" src="//use.typekit.net/wau5wbw.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div id="nav-container"> 
  <%= render 'layouts/nav' %>
</div>
<%= yield %>

</body>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :cover_image %><br>
    <%= f.file_field :cover_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="blog-container">
  <% @posts.each do |post| %>
    <section>
      <h3><%= post.title %></h3>
      <div><%= post.created_at.strftime("%m / %y") %></div>
      <div class="blog-image">
        <%= image_tag(post.cover_image.url) %>
      </div>
      <p><%= post.body %></p>
    </section>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div id="posts-container">
  <%= @post.title %>
  <%= @post.body %>
</div>

app/views/visuals/_form.html.erb
<%= form_for(@visual) do |f| %>
  <% if @visual.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visual.errors.count, "error") %> prohibited this visual from being saved:</h2>

      <ul>
      <% @visual.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visuals/edit.html.erb
<h1>Editing visual</h1>

<%= render 'form' %>

<%= link_to 'Show', @visual %> |
<%= link_to 'Back', visuals_path %>

app/views/visuals/index.html.erb
<h1>Listing visuals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @visuals.each do |visual| %>
      <tr>
        <td><%= visual.title %></td>
        <td><%= visual.description %></td>
        <td><%= link_to 'Show', visual %></td>
        <td><%= link_to 'Edit', edit_visual_path(visual) %></td>
        <td><%= link_to 'Destroy', visual, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visual', new_visual_path %>

app/views/visuals/new.html.erb
<h1>New visual</h1>

<%= render 'form' %>

<%= link_to 'Back', visuals_path %>

app/views/visuals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @visual.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @visual.description %>
</p>

<%= link_to 'Edit', edit_visual_path(@visual) %> |
<%= link_to 'Back', visuals_path %>